#ifndef R_BUILTINS_H
#define R_BUILTINS_H

#include <QStringList>

inline const QStringList &getStandardRBuiltins()
{
    static const QStringList s_rBuiltins = {
        "abbreviate", "ability.cov", "abline", "abs", "acf", "acf2AR", "acos", "acosh",
        "activeBindingFunction", "add.scope", "add1", "addmargins", "addNA", "addNextMethod",
        "addTaskCallback", "adist", "adjustcolor", "aggregate", "aggregate.data.frame",
        "aggregate.ts", "agrep", "agrepl", "AIC", "airmiles", "AirPassengers", "airquality",
        "alarm", "alias", "alist", "all", "all.equal", "all.equal.character", "all.equal.default",
        "all.equal.environment", "all.equal.envRefClass", "all.equal.factor", "all.equal.formula",
        "all.equal.function", "all.equal.language", "all.equal.list", "all.equal.numeric",
        "all.equal.POSIXt", "all.equal.raw", "all.names", "all.vars", "allNames", "allowInterrupts",
        "anova", "ansari.test", "any", "anyDuplicated", "anyNA", "aperm", "append", "apply",
        "approx", "approxfun", "apropos", "ar", "ar.burg", "ar.mle", "ar.ols", "ar.yw", "args",
        "arima", "arima.sim", "arima0", "arima0.diag", "ARMAacf", "ARMAtoMA", "array", "arrayInd",
        "arrows", "as.array", "as.call", "as.character", "as.character.Date", "as.character.default",
        "as.character.factor", "as.character.hexmode", "as.character.numeric_version",
        "as.character.octmode", "as.character.octmode", "as.character.POSIXt", "as.character.srcref",
        "as.complex", "as.data.frame", "as.data.frame.array", "as.data.frame.AsIs",
        "as.data.frame.character", "as.data.frame.complex", "as.data.frame.data.frame",
        "as.data.frame.Date", "as.data.frame.default", "as.data.frame.factor", "as.data.frame.integer",
        "as.data.frame.list", "as.data.frame.logical", "as.data.frame.matrix", "as.data.frame.model.matrix",
        "as.data.frame.numeric", "as.data.frame.numeric_version", "as.data.frame.ordered",
        "as.data.frame.POSIXct", "as.data.frame.POSIXlt", "as.data.frame.raw", "as.data.frame.table",
        "as.data.frame.ts", "as.data.frame.vector", "as.Date", "as.Date.character", "as.Date.default",
        "as.Date.factor", "as.Date.numeric", "as.Date.POSIXct", "as.Date.POSIXlt", "as.difftime",
        "as.double", "as.environment", "as.expression", "as.expression.default", "as.factor",
        "as.formula", "as.function", "as.function.default", "as.graphicsAnnot", "as.hclust",
        "as.hexmode", "as.integer", "as.list", "as.list.data.frame", "as.list.Date", "as.list.default",
        "as.list.environment", "as.list.factor", "as.list.function", "as.list.numeric_version",
        "as.list.POSIXct", "as.list.POSIXlt", "as.logical", "as.matrix", "as.matrix.data.frame",
        "as.matrix.default", "as.matrix.noquote", "as.matrix.POSIXlt", "as.name", "as.null",
        "as.null.default", "as.numeric", "as.numeric_version", "as.octmode", "as.ordered",
        "as.pairlist", "as.person", "as.personList", "as.POSIXct", "as.POSIXct.Date",
        "as.POSIXct.default", "as.POSIXct.numeric", "as.POSIXct.POSIXlt", "as.POSIXlt",
        "as.POSIXlt.character", "as.POSIXlt.Date", "as.POSIXlt.default", "as.POSIXlt.factor",
        "as.POSIXlt.numeric", "as.POSIXlt.POSIXct", "as.qr", "as.raw", "as.relistable", "as.roman",
        "as.single", "as.single.default", "as.symbol", "as.table", "as.table.default", "as.ts",
        "as.vector", "asin", "asinh", "asNamespace", "asS3", "asS4", "assign", "assocplot",
        "atan", "atan2", "atanh", "attach", "attachNamespace", "attr", "attr.all.equal", "attributes",
        "autoload", "autocurry", "ave", "axis", "axis.Date", "axis.POSIXct", "axTicks",
        "backsolve", "bandwidth.kernel", "barplot", "barplot.default", "base", "baseenv", "basename",
        "besselI", "besselJ", "besselK", "besselY", "beta", "bfft", "BIC", "bindingIsActive",
        "bindingIsLocked", "bindtextdomain", "binom.test", "binomial", "biplot", "bitwAnd", "bitwNot",
        "bitwOr", "bitwShiftL", "bitwShiftR", "bitwXor", "body", "box", "boxplot", "boxplot.default",
        "boxplot.matrix", "bquote", "break", "browseEnv", "browseURL", "browseVignettes", "browser",
        "browserCondition", "browserSetDebug", "browserText", "builtins", "by", "by.data.frame",
        "by.default", "bzfile", "c", "c.Date", "c.noquote", "c.numeric_version", "c.POSIXct",
        "c.POSIXlt", "c.warnings", "call", "callCC", "callGeneric", "callNextMethod", "canCoerce",
        "cancor", "capabilities", "capture.output", "casefold", "cat", "cbind", "cbind.data.frame",
        "ccf", "cdplot", "ceiling", "char.expand", "character", "charmatch", "charToRaw", "chartr",
        "check_tzones", "checkCRAN", "chisq.test", "chol", "chol2inv", "choose", "chull",
        "citEntry", "citFooter", "citHeader", "citation", "cite", "citeNatbib", "class", "clearNames",
        "clipboard", "close", "close.connection", "close.srcfile", "close.srcfilealias", "closeAllConnections",
        "cm", "cmdscale", "co2", "coef", "coefficients", "coerce", "col", "colMeans", "colnames",
        "colSums", "commandArgs", "comment", "complete.cases", "complex", "confint", "confint.default",
        "confint.lm", "conflictRules", "conflicts", "conformMethod", "Conj", "conlle", "connection",
        "contr.helmert", "contr.poly", "contr.SAS", "contr.sum", "contr.treatment", "contrasts",
        "contrib.url", "convolve", "cooks.distance", "coplot", "cor", "cor.test", "cos", "cosh",
        "cospi", "count.fields", "cov", "cov.wt", "cov2cor", "covratio", "cpgram", "cross", "crossprod",
        "cumsum", "cumprod", "cummax", "cummin", "curlGetHeaders", "curry", "cut", "cut.Date",
        "cut.default", "cut.POSIXt", "cycle", "dbeta", "dbinom", "dcauchy", "dchisq", "de",
        "debug", "debugcall", "debugger", "debugonce", "decompose", "delay", "deltat", "demo",
        "density", "density.default", "deparse", "deparse1", "deriv", "deriv.default", "deriv.formula",
        "deriv3", "deriv3.default", "deriv3.formula", "det", "detach", "determinant", "dexp", "df",
        "df.residual", "dfbeta", "dfbetas", "dffits", "dgamma", "dgeom", "dhyper", "diag", "diff",
        "diff.Date", "diff.default", "diff.POSIXt", "diff.ts", "difftime", "digamma", "dim",
        "dimnames", "dir", "dir.create", "dir.exists", "dirname", "dist", "dlnorm", "dlogis",
        "dnbinom", "dnorm", "dontCheck", "dpois", "dpsifreq", "drop", "drop.scope", "drop1",
        "drop1.default", "drop1.lm", "droplevels", "droplevels.data.frame", "droplevels.factor",
        "dsignrank", "dt", "dummy.coef", "dump", "dunif", "duplicated", "duplicated.array",
        "duplicated.data.frame", "duplicated.default", "duplicated.matrix", "duplicated.numeric_version",
        "duplicated.POSIXlt", "duplicated.warnings", "dval", "dweibull", "dwilcox", "dyn.load",
        "dyn.unload", "dynGet", "eapply", "ecdf", "edit", "eff.aovlist", "effects", "eigen", "else",
        "emmeans", "emptyenv", "enc2native", "enc2utf8", "encodeString", "end", "environment",
        "environmentIsLocked", "environmentName", "env.profile", "epoch", "erase", "error", "eval",
        "eval.parent", "evalq", "example", "exists", "exp", "expand.grid", "expand.model.frame",
        "expint", "expm1", "expression", "extractAIC", "factanal", "factor", "factor.scope",
        "factorial", "FALSE", "family", "fivenum", "fix", "fixef", "flags", "fligner.test",
        "floor", "flush", "flush.console", "for", "force", "forceAndCall", "formals", "format",
        "format.AsIs", "format.data.frame", "format.Date", "format.default", "format.difftime",
        "format.factor", "format.hexmode", "format.info", "format.numeric_version", "format.octmode",
        "format.POSIXct", "format.POSIXlt", "format.pval", "formatC", "formatDL", "formula",
        "forwardsolve", "Fourfoldplot", "fraction", "friedman.test", "ftable", "function",
        "gamma", "Gamma", "gaussian", "gc", "gc.time", "gcinfo", "gctorture", "gctorture2", "geneplot",
        "general.methods", "get", "get0", "getAllConnections", "getCallingDLL", "getCallingDLLe",
        "getConnection", "getDLLRegisteredRoutines", "getDownloadOption", "getenv", "geterrmessage",
        "getExportedValue", "getFunction", "getGeneric", "getGroup", "getGroupMembers", "getHook",
        "getLoadedDLLs", "getMethod", "getMethods", "getMethodsMetaData", "getModelData", "getNamespace",
        "getNamespaceExports", "getNamespaceImports", "getNamespaceInfo", "getNamespaceName",
        "getNamespaceUsers", "getNamespaceVersion", "getNativeSymbolInfo", "getOption", "getPackageName",
        "getPackageVersion", "getRversion", "getSrcDirectory", "getSrcFilename", "getSrcLocation",
        "getSrcref", "getTaskCallbackNames", "getTextEncoding", "getTxtProgressBar", "getValidity",
        "getwd", "gl", "glm", "glm.control", "glm.fit", "glob2rx", "globalenv", "glyphInfo", "graphics.off",
        "gray", "gray.colors", "grep", "grepl", "grepraw", "grey", "grey.colors", "grid", "grouping",
        "gsub", "gzcon", "gzfile", "hasArg", "hasMethod", "hasMethods", "hasTsp", "hat", "hatvalues",
        "hclust", "head", "head.data.frame", "head.default", "head.matrix", "heat.colors", "heatmap",
        "help", "help.search", "help.start", "hist", "hist.default", "history", "HMD", "hsearch_db",
        "hsv", "I", "identical", "identify", "identify.default", "identity", "ifelse", "IQR",
        "image", "image.default", "importIntoEnv", "in", "index.search", "Inf", "influence",
        "influence.measures", "inherits", "initGeneric", "initMethodDispatch", "initial", "inline",
        "install.packages", "installed.packages", "integer", "integrate", "interaction", "interaction.plot",
        "interactive", "intersect", "intToBits", "intToUtf8", "inverse.gaussian", "invisible",
        "IQR", "iris", "iris3", "is.array", "is.atomic", "is.call", "is.character", "is.complex",
        "is.data.frame", "is.double", "is.element", "is.empty.model", "is.environment", "is.expression",
        "is.factor", "is.finite", "is.function", "is.infinite", "is.integer", "is.language",
        "is.leaf", "is.list", "is.loaded", "is.logical", "is.matrix", "is.mts", "is.na",
        "is.na.data.frame", "is.na.numeric_version", "is.na.POSIXlt", "is.name", "is.nan", "is.null",
        "is.numeric", "is.numeric.Date", "is.numeric.difftime", "is.numeric.POSIXt", "is.numeric_version",
        "is.object", "is.ordered", "is.package_version", "is.pairlist", "is.primitive", "is.qr",
        "is.R", "is.raw", "is.recursive", "is.relistable", "is.single", "is.stepfun", "is.symbol",
        "is.table", "is.ts", "is.tskernel", "is.unsorted", "is.vector", "is.vector.factor",
        "isatty", "isBaseNamespace", "isGeneric", "isGrammarSymbol", "isGroup", "isIncomplete",
        "isNamespace", "isNamespaceLoaded", "isOpen", "isRestart", "isS3method", "isS3stdGeneric",
        "isS4", "isSeekable", "isSymmetric", "isSymmetric.matrix", "isTRUE", "isFALSE",
        "jitter", "kalman", "KalmanForecast", "KalmanLike", "KalmanRun", "KalmanSmooth",
        "kappa", "kappa.default", "kappa.lm", "kappa.qr", "kernel", "kmeans", "knots", "kronecker",
        "kruskal.test", "ks.test", "ksmooth", "l10n_info", "lag", "lag.plot", "La_library", "La.svd",
        "labels", "labels.default", "labels.dist", "labels.lm", "lapply", "layout", "layout.show",
        "lazyLoad", "lazyLoadDBexec", "lazyLoadDBfetch", "lbeta", "lchoose", "lcm", "legend", "length",
        "length.POSIXlt", "levels", "levels.default", "lfactorial", "lgamma", "library", "library.dynam",
        "library.dynam.unload", "licence", "license", "line", "lines", "lines.default", "list",
        "list.dirs", "list.files", "list2DF", "list2env", "lm", "lm.fit", "lm.influence", "lm.wfit",
        "load", "loadedNamespaces", "loadhistory", "loadNamespace", "loadURL", "localeconv",
        "locales", "lockBinding", "lockEnvironment", "loess", "loess.control", "loess.smooth", "log",
        "log10", "log1p", "log2", "logb", "logic", "logical", "logLik", "logLik.glm", "logLik.lm",
        "loglin", "lowess", "ls", "ls.str", "lsf.str", "mad", "mahalanobis", "make.names",
        "make.socket", "make.unique", "makeActiveBinding", "makeARIMA", "makepredictcall",
        "manova", "mantelhaen.test", "mapply", "margin.table", "marginSums", "mat.or.vec",
        "match", "match.arg", "match.call", "match.fun", "matches", "matrix", "matrixStats", "max",
        "max.col", "mcnemar.test", "mean", "mean.Date", "mean.default", "mean.difftime",
        "mean.POSIXct", "mean.POSIXlt", "median", "median.default", "medpolish", "mem.limits",
        "memCompress", "memDecompress", "memory.limit", "memory.profile", "memory.size", "menu",
        "merge", "merge.data.frame", "merge.default", "message", "mget", "min", "missing", "Mod",
        "mode", "model.extract", "model.frame", "model.frame.default", "model.matrix",
        "model.matrix.default", "model.matrix.lm", "model.offset", "model.response", "model.weights",
        "month.abb", "month.name", "months", "months.Date", "months.POSIXt", "mosaicplot", "mpfr",
        "mtext", "multinom", "na.action", "na.contiguous", "na.exclude", "na.fail", "na.omit",
        "na.omit.data.frame", "na.omit.default", "na.pass", "NA", "NA_character_", "NA_complex_",
        "NA_integer_", "NA_real_", "names", "names.POSIXlt", "namespaceExport", "namespaceImport",
        "namespaceImportClasses", "namespaceImportFrom", "namespaceImportMethods", "NaN", "naprint",
        "nargs", "nchar", "ncol", "NCOL", "new", "new.env", "next", "NextMethod", "nextn",
        "ngettext", "nlevels", "nlm", "nlminb", "nls", "nls.control", "nls.fit", "Nmissing",
        "nobs", "nobs.default", "nobs.glm", "nobs.lm", "nonzeros", "noquote", "norm", "normalizePath",
        "nrow", "NROW", "NULL", "numeric", "numeric_version", "numericDeriv", "objects", "offset",
        "old.packages", "on.exit", "open", "open.connection", "open.srcfile", "open.srcfilealias",
        "open.srcfilecopy", "optim", "optimHess", "optimise", "optimize", "options", "order",
        "ordered", "outer", "pacman", "package.skeleton", "packageDescription", "packageEvent",
        "packageName", "packageNotFoundError", "packageStartupMessage", "packageVersion", "packBits",
        "page", "pairlist", "pairs", "pairs.default", "palette", "palette.colors", "palette.pals",
        "panelfirst", "paper", "parallel", "parent.env", "parent.frame", "parse", "parseNamespaceFile",
        "paste", "paste0", "path.expand", "path.package", "pbeta", "pbinom", "pbirthday", "pcauchy",
        "pchisq", "pdata", "penn50", "period", "persp", "pexp", "pf", "pgamma", "pgeom", "phyper",
        "pi", "pie", "pipe", "pixel", "pkg2HTML", "pkgDepends", "plclust", "pllog", "plnorm",
        "plogis", "plot", "plot.default", "plot.design", "plot.ecdf", "plot.function", "plot.lm",
        "plot.mlm", "plot.new", "plot.spec", "plot.stepfun", "plot.ts", "plot.window", "plot.xy",
        "pmatch", "pmax", "pmax.int", "pmin", "pmin.int", "pnbinom", "pnorm", "points", "points.default",
        "poibin", "poisson", "poly", "polym", "polyroot", "pos.to.env", "POSIXct", "POSIXlt",
        "power", "power.anova.test", "power.prop.test", "power.t.test", "PP.test", "ppoints",
        "ppois", "ppr", "prcomp", "prcomp.default", "precision", "predict", "predict.glm",
        "predict.lm", "predict.loess", "predict.nls", "predict.poly", "predict.ppr", "predict.prcomp",
        "predict.princomp", "predict.smooth.spline", "preplot", "pretty", "pretty.default", "prettyNum",
        "princomp", "princomp.default", "print", "print.anova", "print.atomic", "print.by",
        "print.coefmat", "print.data.frame", "print.Date", "print.default", "print.difftime",
        "print.dummy.coef", "print.factor", "print.family", "print.formula", "print.ftable",
        "print.glm", "print.hclust", "print.hexmode", "print.infl", "print.integrate", "print.libraryIQR",
        "print.listof", "print.lm", "print.logLik", "print.medpolish", "print.noquote",
        "print.numeric_version", "print.octmode", "print.packageInfo", "print.pairwise.htest",
        "print.person", "print.POSIXct", "print.POSIXlt", "print.power.htest", "print.ppr",
        "print.prcomp", "print.princomp", "print.proc_time", "print.qr", "print.rle", "print.simple.list",
        "print.smooth.spline", "print.socket", "print.srcfile", "print.summary.aov",
        "print.summary.glm", "print.summary.lm", "print.summary.loess", "print.summary.manova",
        "print.summary.nls", "print.summary.prcomp", "print.summary.princomp", "print.summary.table",
        "print.table", "print.terms", "print.ts", "print.tskernel", "print.tukeyline", "print.warnings",
        "prmatrix", "proc.time", "profile", "profile.glm", "profile.nls", "proj", "promFetch",
        "prompt", "promptData", "promptPackage", "prop.table", "prop.test", "prop.trend.test",
        "provide", "provideDimnames", "ps.options", "pseudo", "psigamma", "psignrank", "pt", "ptukey",
        "punif", "pweibull", "pwilcox", "q", "qbeta", "qbinom", "qbirthday", "qcauchy", "qchisq",
        "qexp", "qf", "qgamma", "qgeom", "qhyper", "qlnorm", "qlogis", "qnbinom", "qnorm", "qpois",
        "qqline", "qqnorm", "qqnorm.default", "qqplot", "qr", "qr.coef", "qr.default", "qr.detail",
        "qr.fitted", "qr.Q", "qr.qty", "qr.qy", "qr.R", "qr.resid", "qr.solve", "qr.X", "qsignrank",
        "qt", "qtukey", "quade.test", "quantile", "quantile.default", "quarters", "quarters.Date",
        "quarters.POSIXt", "quasi", "quasibinomial", "quasipoisson", "quit", "qunif", "quote",
        "qweibull", "qwilcox", "R.home", "R.Version", "R.version", "R.version.string", "rainbow",
        "range", "range.default", "rank", "rapply", "raw", "rawConnection", "rawConnectionValue",
        "rawShift", "rawToBits", "rawToChar", "rbeta", "rbind", "rbind.data.frame", "rbinom",
        "rcauchy", "rchisq", "RColorBrewer", "Rd_parse", "rDevice", "read.csv", "read.csv2",
        "read.delim", "read.delim2", "read.DIF", "read.fortran", "read.ftable", "read.fwf",
        "read.socket", "read.table", "readBin", "readChar", "readCitationFile", "readline",
        "readLines", "readRDS", "readRegistry", "Recall", "recordGraphics", "recordPlot", "recover",
        "rect", "rect.hclust", "reformulate", "reg.finalizer", "regexec", "regexp", "regexpr",
        "registerS3method", "registerS3methods", "regmatches", "relevel", "relevel.default",
        "relevel.factor", "reload", "relist", "rem", "remove", "remove.packages", "removeBin",
        "removeTaskCallback", "rep", "rep.Date", "rep.default", "rep.factor", "rep.int", "rep.len",
        "rep.numeric_version", "rep.POSIXct", "rep.POSIXlt", "repeat", "replace", "replicate",
        "replications", "reply", "require", "requireNamespace", "reset", "reshape", "resid",
        "residuals", "residuals.default", "residuals.glm", "residuals.lm", "residuals.nls",
        "restartDescription", "restartFormals", "retracemem", "return", "rev", "rev.default",
        "rexp", "rf", "rgamma", "rgb", "rgb2hsv", "rgeom", "rhyper", "rle", "rlnorm", "rlogis",
        "rm", "rmultinom", "rnbinom", "RNGkind", "RNGversion", "rnorm", "round", "round.Date",
        "round.POSIXt", "row", "row.names", "row.names.data.frame", "row.names.default", "rowMeans",
        "rownames", "rowsum", "rowsum.data.frame", "rowsum.default", "rowSums", "rpois", "rsignrank",
        "rstandard", "rstandard.glm", "rstandard.lm", "rstudent", "rstudent.glm", "rstudent.lm",
        "rt", "rug", "runif", "runmed", "rweibull", "rwilcox", "sample", "sample.int", "sapply",
        "save", "save.image", "savehistory", "savePlot", "saveRDS", "scale", "scale.default",
        "scan", "scatter.smooth", "screeplot", "sd", "sd.default", "se.contrast", "seek",
        "seek.connection", "segments", "select.list", "selectMethod", "selfStart", "seq",
        "seq.Date", "seq.default", "seq.int", "seq.POSIXt", "seq_along", "seq_len", "sequence",
        "serialize", "sessionInfo", "set.seed", "setdiff", "setequal", "setGeneric", "setGroupGeneric",
        "setHook", "setIs", "setMethod", "setMethodsMetaData", "setNamespaceInfo", "setOldClass",
        "setPackageName", "setRefClass", "sets", "setSessionTimeLimit", "setTimeLimit", "setTxtProgressBar",
        "setValidity", "setwd", "shapiro.test", "show", "showConnections", "showMethods", "shutdown",
        "sign", "signalCondition", "signature", "signif", "simpleCondition", "simpleError",
        "simpleMessage", "simpleWarning", "sin", "single", "sinh", "sink", "sink.number", "sinpi",
        "slice.index", "smooth", "smooth.spline", "smoothEnds", "socketAccept", "socketConnection",
        "socketListen", "socketSelect", "socketTimeout", "solve", "solve.default", "solve.qr",
        "sort", "sort.data.frame", "sort.default", "sort.int", "sort.list", "sort.POSIXlt",
        "source", "spectrum", "spline", "splinefun", "split", "split.data.frame", "split.Date",
        "split.default", "split.POSIXct", "sprintf", "sqrt", "srcfile", "srcfilealias", "srcfilecopy",
        "srcref", "stack", "standardGeneric", "standardGenericSelf", "standardMethods", "star",
        "stars", "start", "stat.anova", "step", "stepfun", "stl", "stop", "stopifnot", "storage.mode",
        "str", "str.data.frame", "str.default", "strftime", "strOptions", "strptime", "strrep",
        "strsplit", "structure", "strtrim", "strwidth", "sub", "substitute", "substr", "substring",
        "summary", "summary.aov", "summary.connection", "summary.data.frame", "summary.Date",
        "summary.default", "summary.factor", "summary.glm", "summary.infl", "summary.lm",
        "summary.loess", "summary.manova", "summary.matrix", "summary.mlm", "summary.nls",
        "summary.packageIQR", "summary.POSIXct", "summary.POSIXlt", "summary.ppr", "summary.prcomp",
        "summary.princomp", "summary.proc_time", "summary.srcfile", "summary.stepfun", "summary.table",
        "summary.ts", "summaryRprof", "sunspot.month", "sunspot.year", "sunspots", "suppressForeignCheck",
        "suppressMessages", "suppressPackageStartupMessages", "suppressWarnings", "svd", "sweep",
        "symbols", "symnum", "sys.call", "sys.calls", "sys.frame", "sys.frames", "sys.function",
        "sys.nframe", "sys.on.exit", "sys.parent", "sys.parents", "sys.save.image", "sys.source",
        "sys.status", "Sys.chmod", "Sys.Date", "Sys.getenv", "Sys.getlocale", "Sys.getpid",
        "Sys.glob", "Sys.info", "Sys.localeconv", "Sys.readlink", "Sys.setenv", "Sys.setFileTime",
        "Sys.setlocale", "Sys.sleep", "Sys.time", "Sys.timezone", "Sys.umask", "Sys.unsetenv",
        "Sys.which", "system", "system.file", "system.time", "system2", "t", "t.data.frame",
        "t.default", "t.test", "table", "tabulate", "tail", "tail.data.frame", "tail.default",
        "tail.matrix", "tan", "tanh", "tanpi", "tapply", "tar", "taskCallbackManager", "tcrossprod",
        "tempdir", "tempfile", "terms", "terms.default", "terms.formula", "terrain.colors", "testPlatform",
        "testPlatformEquivalence", "text", "text.default", "textConnection", "textConnectionValue",
        "tiff", "time", "timestamp", "title", "tm", "toBibtex", "toeplitz", "tolower", "topenv",
        "topo.colors", "toString", "toString.default", "toupper", "trace", "traceback", "tracemem",
        "tracingState", "transform", "transform.data.frame", "transform.default", "trellis.par.get",
        "trellis.par.set", "trimws", "TRUE", "trunc", "trunc.Date", "trunc.POSIXt", "truncate",
        "truncate.connection", "try", "tryCatch", "ts", "ts.intersect", "ts.plot", "ts.union",
        "tsdiag", "tsp", "tsSmooth", "tsTest", "tukey.kramer", "TukeyHSD", "TukeyHSD.aov",
        "type.convert", "typeof", "unclass", "undebug", "undo", "undoc", "unembed", "unformat",
        "uniform", "uniroot", "unique", "unique.array", "unique.data.frame", "unique.default",
        "unique.matrix", "unique.numeric_version", "unique.POSIXlt", "unique.warnings", "unit",
        "unlink", "unlockBinding", "unname", "unserialize", "unset", "unsplit", "unstack",
        "untrace", "untracemem", "unz", "update", "update.default", "update.formula", "update.packages",
        "update.packages.gui", "upgrade", "upper.tri", "url", "url.show", "UseMethod", "utf8ToInt",
        "validDetails", "validityMethod", "validObject", "vapply", "var", "var.test", "variable.names",
        "varimax", "vcov", "vector", "Vectorize", "vi", "View", "vignette", "vintage", "volcano",
        "warning", "warningCondition", "warnings", "weighted.mean", "weighted.residuals", "weights",
        "which", "which.max", "which.min", "while", "wilcox.test", "window", "with", "with.default",
        "withAutoprint", "within", "within.data.frame", "within.list", "withRestarts", "withVisible",
        "women", "write", "write.csv", "write.csv2", "write.dcf", "write.ftable", "write.table",
        "writeBin", "writeChar", "writeLines", "wsbrowser", "x11", "xedit", "xemacs", "xinch",
        "xor", "xpdrows", "xspline", "xtabs", "xtfrm", "xtfrm.Date", "xtfrm.default", "xtfrm.difftime",
        "xtfrm.factor", "xtfrm.numeric_version", "xtfrm.POSIXct", "xtfrm.POSIXlt", "xVector",
        "xy.coords", "xyinch", "xyz.coords", "xzfile", "yinch", "zapsmall", "zip"
    };
    return s_rBuiltins;
}

#endif // R_BUILTINS_H
